name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lab 01 - STRCPY Verification
      id: lab-01-strcpy-verification
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Lab 01 - STRCPY Verification
        setup-command: sudo apt-get update && sudo apt-get install -y iverilog gcc-aarch64-linux-gnu
          binutils-aarch64-linux-gnu
        command: bash .github/classroom/lab01_test.sh
        timeout: 10
        max-score: 10
    - name: Lab 00 - Environment Check
      id: lab-00-environment-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Lab 00 - Environment Check
        setup-command: ''
        command: bash .github/classroom/lab00_test.sh
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LAB-01-STRCPY-VERIFICATION_RESULTS: "${{steps.lab-01-strcpy-verification.outputs.result}}"
        LAB-00-ENVIRONMENT-CHECK_RESULTS: "${{steps.lab-00-environment-check.outputs.result}}"
      with:
        runners: lab-01-strcpy-verification,lab-00-environment-check
